## Importation des librairies
```{r}
library(gsheet)
library(dplyr)
library(tidyr)
library(readr)
```

## Importer les données depuis un fichier csv
dataLab2 <- readr::read_csv("./lab2_data.csv")

## Importer les données depuis googlesheet
```{r}
mydata <- gsheet::gsheet2tbl("https://docs.google.com/spreadsheets/d/1uLaXke-KPN28-ESPPoihk8TiXVWp5xuNGHW7w7yqLCc/edit#gid=416085055")
```

## Exemple de piping "tuyauterie" avec glimpse() qui permet d'afficher le nombre de lignes et le nombre de colonnes et donne un aperçu du contenu de chaque colonne
```{r}
mydata %>%
  glimpse()
```
## Afficher les six (06) premières lignes du dataframe
```{r}
head(mydata)
```
## Ajouter une nouvelle colonne
```{r}
mydata$newColumn <- 45
```

## Noms des colonnes
```{r}
colnames(mydata)
```
## Six (06) premières lignes d'une colonne spécifique
```{r}
head(mydata[,"year"])
```
## Calcule avec des colonnes et sauvegarde de la réponse dans une colonne
```{r}
mydata$newColumn <- mydata$newColumn * 2 + 5
```

## Renommer une colonne
```{r}
mydata <- mydata %>% 
  dplyr::rename(newColumnRenamed = newColumn)
colnames(mydata)
```
## Supprimer une colonne
```{r}
mydata$newColumnRenamed <- NULL

colnames(mydata)
```
## Voir la dimension du dataframe
```{r}
dim(mydata)
```
## Filtrer les données dans le dataframe
```{r}
datafiltred <- filter(mydata, year == 2010)
```

## Trier les données
```{r}
datasorted <- arrange(mydata, year)

datareverse <- arrange(mydata, desc(year))
```

## 